apiVersion: apps/v1
kind: Deployment
metadata:
  name: auxiliarcontable
  namespace: marshando-backend
spec:
  selector:
    matchLabels:
      app: auxiliarcontable
  replicas: 1
  template:
    metadata:
      labels:
         app: auxiliarcontable
    spec:
      imagePullSecrets:
         - name: github-secret
      containers:
         - name: auxiliarcontable
           image: localhost:5000/api-auxiliarcontable 
           ports:
              - containerPort: 8080
           env:
              - name: db_host
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: db_host
              - name: db_usuario
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: db_usuario
              - name: db_contrasena
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: db_contrasena
              - name: db_basedatos_auxiliar_contable
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: db_basedatos_auxiliar_contable
              - name: autorizacion_urlAutorizacion
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: autorizacion_urlAutorizacion
              - name: autorizacion_urlAutorizacionBase
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: autorizacion_urlAutorizacionBase
              - name: autorizacion_urlAutorizacionUsuario
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: autorizacion_urlAutorizacionUsuario
              - name: autorizacion_urlAutorizacionAplicacion
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: autorizacion_urlAutorizacionAplicacion
              - name: archivos_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: archivos_url
              - name: datos_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: datos_url
              - name: autorizacion_codigo_auxiliar_contable
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: autorizacion_codigo_auxiliar_contable
              - name: casos_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: casos_url
              - name: contabilidad_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: contabilidad_url
              - name: facturas_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: facturas_url
              - name: gastos_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: gastos_url
              - name: ingresoNoOperacional_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: ingresoNoOperacional_url
              - name: nomina_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: nomina_url
              - name: sucursales_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: sucursales_url
              - name: terceros_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: terceros_url
              - name: cajaCuentaBancos_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: cajaCuentaBancos_url
              - name: impuestos_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: impuestos_url
              - name: usuarioBaseDatosPrincipal_mongodb
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: usuarioBaseDatosPrincipal_mongodb
              - name: contrasenaBaseDatosPrincipal_mongodb
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: contrasenaBaseDatosPrincipal_mongodb
              - name: hostBaseDatosPrincipal_mongodb
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: hostBaseDatosPrincipal_mongodb
              - name: puerto_mongodb
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: puerto_mongodb
              - name: baseDatosPrincipal_mongodb
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: baseDatosPrincipal_mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: auxiliarcontable
  namespace: marshando-backend
spec:
#  type: NodePort
  selector:
    app: auxiliarcontable
  ports:
    - protocol: TCP
      port: 8080
#      nodePort: 30001
      targetPort: 8080